Don't use "[1,2].includes()" construct, seems that packaging breaks it
Causes:

TypeError: undefined is not a function (evaluating '["articles","article"].includes((0,_utils.last)(state.routeStack).name)')